services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - app_data:/app/data
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped

volumes:
  app_data: